name: Action 

on: push
  # schedule:
  #   - cron: '0 3 * * *'
  # push:
    # branches:
    #   - master
  # workflow_dispatch:
        
jobs:
  build:  
    runs-on: ubuntu-latest 
    steps:
      - name: environment setting
        env:
          line_apikey: ${{secrets.LINE_APIKEY}}	   
      - uses: actions/checkout@v2
      - name: Setup python 
        uses: actions/setup-python@v2 
        with:
          python-version: "3.10" 
      - name: Install dependencies 
        run: pip install -r requirements.txt
      - name: Run Python
        run: python fetch_news.py ${line_apikey}

      